version: '3.3'

services:

  droppy:
    image: silverwind/droppy
    container_name: droppy    
    ports:
      - '8200:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid      
    volumes:
      - ./config:/config
      - ./data:/files
    restart: unless-stopped

    
